pub mod pattern_table;
mod flags;
mod addressing;
mod rendering;
mod oam;
mod sprite_buffer_memory;

use core::panic;
use std::{usize};

use image::Rgb;

use super::{nes_parser::NametableArrangement, ppu::{flags::{PPUCTRL, PPUMask, PPUReg, PPUStatus}, oam::OAM, sprite_buffer_memory::BufferSprite}};


pub struct PPU {
    color_data: [Rgb<u8>; 64],
    ctrl: PPUCTRL,
    mask: PPUMask,
    status: PPUStatus,
    oam_addr: u8,
    xscroll: u8,
    yscroll: u8,
    addr: u8,
    addressor: addressing::PPUMemoryMap,
    oam: OAM,
    // Internal registers
    v: u16, // Current VRAM address (15 bits)
    t: u16, // Temporary VRAM address (15 bits)
    x: u8,  // Fine X scroll (3 bits)
    w: bool,  // 1st or 2nd write toggle
              //
    cycle: usize, // Rendering cycle
    scanline: usize,

    ppu_read_buffer: u8, // R/W to PPUdata are buffered

    pattern_data_lb: u16,
    pattern_data_hb: u16,

    sprite_buffer_data: [BufferSprite; 8],
    
    attribute_data_lb: u16,
    attribute_data_hb: u16,

    // Generated by the PPU
    image_out: Vec<u8>,
    image_ready: bool,

    // Line status of NMI signal out of PPU
    nmi_lineout: bool,

    // Signals if the NMI that caused the lineout has been
    // processed
    pending_nmi: bool,
}

impl PPU {
    pub fn new(chr_data: &[u8], nametable_arrangement: NametableArrangement, color_data: &[Rgb<u8>]) -> Self {
        Self {
            mask: PPUMask::empty(),
            status: PPUStatus::VBLANK,
            oam_addr: 0,
            addr: 0,
            ctrl: PPUCTRL::empty(),
            xscroll: 0,
            yscroll: 0,
            nmi_lineout: false,
            pending_nmi: false,
            cycle: 0,
            scanline: 0,
            v: 0,
            t: 0,
            x: 0,
            w: false,
            color_data: color_data.try_into().unwrap(),
            oam: OAM::new(),
            addressor: addressing::PPUMemoryMap::new(chr_data, nametable_arrangement),
            image_out: vec![0u8; rendering::IMG_SIZE],
            image_ready: true,
            ppu_read_buffer: 0,

            sprite_buffer_data: [BufferSprite::new(); 8],

            pattern_data_lb: 0,
            pattern_data_hb: 0,
            attribute_data_lb: 0,
            attribute_data_hb: 0,
        }
    }

    pub fn write(&mut self, addr: u8, data: u8) {
        match addr {
            PPUReg::CTRL => {
                self.ctrl = PPUCTRL::from_bits_retain(data); 
                self.t = (self.t & !0x0C00) | ((data as u16 & 0x3) << 10);
            }
            PPUReg::MASK => { self.mask = PPUMask::from_bits_retain(data); }
            PPUReg::STATUS => {  }
            PPUReg::OAMADDR => { self.oam_addr = data; }
            PPUReg::OAMDATA => {
                self.oam.sprites[self.oam_addr as usize] = data;
                self.oam_addr = self.oam_addr.wrapping_add(1);
            }
            PPUReg::SCROLL => {  
                // Writes to scroll changes xscroll and yscroll
                // depending on the order of writes.
                if self.w  {
                    self.yscroll = data;
                    self.t = (self.t & !0x73E0)  |
                        (((data & 0x07) as u16) << 12) | 
                        (((data >> 3) as u16 & 0x1F) << 5);

                } else {
                    self.xscroll = data;
                    self.x = data & 0x07;
                    self.t = (self.t & 0xFFE0) |  ((data >> 3) as u16);
                }
                self.w = !self.w;
            }
            PPUReg::ADDR => { 
                self.addr = data; 

                //Like PPUSCROLL, writing depends on the state of w
                //Effectively, the high and low byte is set on every other write
                if self.w {
                    self.t = (self.t & 0xFF00) | data as u16;
                    self.t &= !(1 << 14);
                    self.v = self.t;
                } else {
                    self.t = (self.t & 0x00FF) | (((data & 0x3F) as u16) << 8);
                }

                self.w = !self.w;
            }
            PPUReg::DATA => {
                // TODO: this behavior only models PPU r/ws when *not* rendering
                // When rendering, the behavior is different, see wiki.
                self.addressor.write(self.v, data);
                self.v = self.v.wrapping_add(if self.ctrl.contains(PPUCTRL::VRAM_INCREMENT) { 32 } else { 1 }) & 0x7FFF;
                
            }
            _ => panic!("Bad PPU address")
        }

        //println!("Writing to {:04X} = {:02X}", addr, data);
    }

    //Writing to address 0x4014 is OAMDMA
    pub fn write_oam_dma(&mut self, data: &[u8], offset: u8) { 
        self.oam.from_dma(offset, &data);
    }

    pub fn read(&mut self, addr: u8) -> u8 {
        let ret = match addr { 
            PPUReg::CTRL => { 
                self.ctrl.bits()
            } 
            PPUReg::MASK => { self.mask.bits() }
            PPUReg::STATUS => { 
                self.w = false;
                let temp = self.status.bits();
                self.status &= PPUStatus::VBLANK;
                temp
            }
            PPUReg::OAMADDR => { self.oam_addr }
            PPUReg::OAMDATA => { self.oam.sprites[self.oam_addr as usize] }
            PPUReg::SCROLL => { self.xscroll }
            PPUReg::ADDR => { self.addr }
            PPUReg::DATA => { 
                let ret = if self.v >= 0x3000 {
                    self.ppu_read_buffer = self.addressor.read(self.v - 0x1000);
                    self.addressor.read(self.v)
                } else {
                    let buf = self.ppu_read_buffer;
                    self.ppu_read_buffer = self.addressor.read(self.v);
                    buf
                };
                self.v = self.v.wrapping_add(if self.ctrl.contains(PPUCTRL::VRAM_INCREMENT) { 32 } else { 1 }) & 0x7FFF;
                ret
            }
            _ => panic!("Bad PPU address")
        };
        //println!("Reading from {} = {}", addr, ret);
        ret
    }

    pub fn pending_nmi(&self) -> bool { self.pending_nmi }
    pub fn clear_nmi(&mut self) { self.pending_nmi = false; self.nmi_lineout = false; }

    pub fn get_image_bytes(&mut self) -> &Vec<u8> { 
        self.image_ready = false; return &self.image_out;
    }

    // **
    // CTRL Flags
    // **
    //fn vram_increment_bit(&self) -> bool { (self.ctrl & (1 << 2)) != 0 }
    //fn sprite_pattern_table_base(&self) -> u16 { if (self.ctrl & (1 << 3)) != 0 { 0x1000 } else { 0 }}
    //fn base_background_pattern_address(&self) -> u16   { if (self.ctrl & (1 << 4)) != 0 { 0x1000 } else { 0 }}
    //fn vblank_nmi_enable(&self) -> bool   { (self.ctrl & (1 << 7)) != 0 }
    //
    //// **
    //// MASK flags
    //// **
    //fn greyscale(&self) -> bool         { return (self.mask & 0x01) != 0; }
    //fn enable_background(&self) -> bool { return (self.mask & 0x08) != 0; }
    //fn enable_sprites(&self) -> bool    { return (self.mask & 0x10) != 0; }


    pub fn image_ready(&self) -> bool { return self.image_ready; }
}
