pub mod pattern_table;
mod addressing;
mod rendering;
mod oam;
mod sprite_buffer_memory;

use core::panic;
use std::{usize};

use bytemuck::offset_of;
use image::Rgb;

use crate::{nes_parser::NametableArrangement, ppu::{oam::OAM, sprite_buffer_memory::BufferSprite}};


pub struct PPU {
    color_data: [Rgb<u8>; 64],
    ctrl: u8,
    mask: u8,
    status: u8,
    oam_addr: u8,
    xscroll: u8,
    yscroll: u8,
    addr: u8,
    data: u8,
    addressor: addressing::PPUMemoryMap,
    oam: OAM,
    // Internal registers
    v: u16, // Current VRAM address (15 bits)
    t: u16, // Temporary VRAM address (15 bits)
    x: u8,  // Fine X scroll (3 bits)
    w: bool,  // 1st or 2nd write toggle
              //
    cycle: usize, // Rendering cycle
    scanline: usize,

    pattern_data_lb: u16,
    pattern_data_hb: u16,

    sprite_buffer_data: [BufferSprite; 8],
    
    attribute_data_lb: u16,
    attribute_data_hb: u16,

    // Generated by the PPU
    image_out: Vec<u8>,
    image_ready: bool,

    // Line status of NMI signal out of PPU
    nmi_lineout: bool,

    // Signals if the NMI that caused the lineout has been
    // processed
    pending_nmi: bool,
}

impl PPU {
    pub fn new(chr_data: &[u8], nametable_arrangement: NametableArrangement, color_data: &[Rgb<u8>]) -> Self {
        Self {
            data: 0,
            mask: 0,
            status: 0x80,
            oam_addr: 0,
            addr: 0,
            ctrl: 0,
            xscroll: 0,
            yscroll: 0,
            nmi_lineout: false,
            pending_nmi: false,
            cycle: 0,
            scanline: 0,
            v: 0,
            t: 0,
            x: 0,
            w: false,
            color_data: color_data.try_into().unwrap(),
            oam: OAM::new(),
            addressor: addressing::PPUMemoryMap::new(chr_data, nametable_arrangement),
            image_out: vec![0u8; rendering::IMG_SIZE],
            image_ready: true,

            sprite_buffer_data: [BufferSprite::new(); 8],

            pattern_data_lb: 0,
            pattern_data_hb: 0,
            attribute_data_lb: 0,
            attribute_data_hb: 0,
        }
    }

    pub fn write(&mut self, addr: u8, data: u8) {
        match addr {
            0 => { // PPUCTRL
                self.ctrl = data; 
                self.t = (self.t & !0x0C00) | ((data as u16 & 0x3) << 10);
            }
            1 => { self.mask = data; }
            2 => { self.status = data; }
            3 => { self.oam_addr = data; }
            4 => {  //OAMADDR
                self.oam.sprites[self.oam_addr as usize] = data;
                self.oam_addr = self.oam_addr.wrapping_add(1);
            }
            5 => {  //PPUSCROLL
                // Writes to scroll changes xscroll and yscroll
                // depending on the order of writes.
                if self.w  {
                    self.yscroll = data;
                    self.t = (self.t & !0x73E0)  |
                        (((data & 0x07) as u16) << 12) | 
                        (((data >> 3) as u16 & 0x1F) << 5);

                } else {
                    self.xscroll = data;
                    self.x = data & 0x07;
                    self.t = (self.t & 0xFFE0) |  ((data >> 3) as u16);
                }
                self.w = !self.w;
            }
            6 => { //PPUADDR
                self.addr = data; 

                if self.w {
                    self.t = (self.t & 0xFF00) | data as u16;
                    self.v = self.t;
                } else {
                    self.t = (self.t & 0x00FF) | (((data & 0x3F) as u16) << 8);
                }

                self.t &= !(1 << 14);
                self.w = !self.w;
            }
            7 => {  //PPUDATA
                // TODO: this behavior only models PPU r/ws when *not* rendering
                // When rendering, the behavior is different, see wiki.
                self.data = data; 
                self.addressor.write(self.v, data);
                self.v = self.v.wrapping_add(if self.vram_increment_bit() { 32 } else { 1 }) & 0x7FFF;
            }
            _ => panic!("Bad PPU address")
        }

        //println!("Writing to {:04X} = {:02X}", addr, data);
    }

    //Writing to address 0x4014 is OAMDMA
    pub fn write_oam_dma(&mut self, data: &[u8], offset: u8) { 
        self.oam.from_dma(offset, &data);
    }

    pub fn read(&mut self, addr: u8) -> u8 {
        let ret = match addr { //PPUCTRL
            0 => { 
                self.ctrl 
            } 
            1 => { self.mask }
            2 => { // PPUSTATUS
                self.w = false;
                let temp = self.status;
                self.status &= !(0x80); //Unset vblank flag
                temp
            }
            3 => { self.oam_addr }
            4 => { self.oam.sprites[self.oam_addr as usize] }
            5 => { self.xscroll }
            6 => { self.addr }
            7 => { 
                self.v = self.v.wrapping_add(if self.vram_increment_bit() { 32 } else { 1 }) & 0x7FFF;
                self.data
            }
            _ => panic!("Bad PPU address")
        };
        //println!("Reading from {} = {}", addr, ret);
        ret
    }

    pub fn pending_nmi(&self) -> bool { self.pending_nmi }
    pub fn clear_nmi(&mut self) { self.pending_nmi = false; self.nmi_lineout = false; }

    pub fn get_image_bytes(&mut self) -> &Vec<u8> { 
        self.image_ready = false; return &self.image_out;
    }

    // **
    // CTRL Flags
    // **
    fn base_nametable_addr(&self) -> u8 {
        self.ctrl & 0x03 
    }
    fn vram_increment_bit(&self) -> bool { (self.ctrl & (1 << 2)) != 0 }
    fn sprite_pattern_table_base(&self) -> u16 { if (self.ctrl & (1 << 3)) != 0 { 0x1000 } else { 0 }}
    fn base_background_pattern_address(&self) -> u16   { if (self.ctrl & (1 << 4)) != 0 { 0x1000 } else { 0 }}
    fn sprite_size(&self) -> (usize, usize)   { if (self.ctrl & (1 << 5)) != 0 { (8, 16) } else { (8, 8) }}
    fn master_slave_select(&self) -> bool   { (self.ctrl & (1 << 6)) != 0 }
    fn vblank_nmi_enable(&self) -> bool   { (self.ctrl & (1 << 7)) != 0 }
    
    // **
    // MASK flags
    // **
    fn greyscale(&self) -> bool              { return (self.mask & 0x1) != 0; }
    fn show_bg_leftmost_screen(&self) -> bool   { return (self.mask & 0x2) != 0; }
    fn show_sprites_leftmost_screen(&self) -> bool  { return (self.mask & 0x4) != 0; }
    fn enable_background(&self) -> bool         { return (self.mask & 0x8) != 0; }
    fn enable_sprites(&self) -> bool         { return (self.mask & 0x10) != 0; }
    fn emphasize_red(&self) -> bool         { return (self.mask & 0x20) != 0; }
    fn emphasize_green(&self) -> bool         { return (self.mask & 0x40) != 0; }
    fn emphasize_blue(&self) -> bool         { return (self.mask & 0x80) != 0; }


    pub fn image_ready(&self) -> bool { return self.image_ready; }
}
