pub mod pattern_table;
mod addressing;

use core::panic;
use std::{usize};

use image::Rgb;

use crate::nes_parser::NametableArrangement;

const IMG_WIDTH: usize = 256;
const IMG_HEIGHT: usize = 240;
const BYTES_PER_PIXEL: usize = 4;
const IMG_SIZE: usize = IMG_HEIGHT*IMG_WIDTH*BYTES_PER_PIXEL;

pub struct PPU {
    color_data: [Rgb<u8>; 64],

    ctrl: u8,
    mask: u8,
    status: u8,
    oam_addr: u8,
    oam_data: u8,
    xscroll: u8,
    yscroll: u8,
    addr: u8,
    data: u8,
    oam_dma: u8,
    addressor: addressing::PPUMemoryMap,

    // Internal registers
    v: u16, // Current VRAM address (15 bits)
    t: u16, // Temporary VRAM address (15 bits)
    x: u8,  // Fine X scroll (3 bits)
    w: bool,  // 1st or 2nd write toggle
              //
    cycle: usize, // Rendering cycle
    scanline: usize,

    pattern_data_lb: u16,
    pattern_data_hb: u16,
    
    attribute_data_lb: u16,
    attribute_data_hb: u16,

    // Generated by the PPU
    image_out: Vec<u8>,
    image_ready: bool,

    // Line status of NMI signal out of PPU
    nmi_lineout: bool,

    // Signals if the NMI that caused the lineout has been
    // processed
    pending_nmi: bool,
}

impl PPU {
    pub fn new(chr_data: &[u8], nametable_arrangement: NametableArrangement, color_data: &[Rgb<u8>]) -> Self {
        Self {
            data: 0,
            mask: 0,
            status: 0x80,
            oam_addr: 0,
            oam_data: 0,
            addr: 0,
            oam_dma: 0,
            ctrl: 0,
            xscroll: 0,
            yscroll: 0,
            nmi_lineout: false,
            pending_nmi: false,
            cycle: 0,
            scanline: 0,
            v: 0,
            t: 0,
            x: 0,
            w: false,
            color_data: color_data.try_into().unwrap(),
            addressor: addressing::PPUMemoryMap::new(chr_data, nametable_arrangement),
            image_out: vec![0u8; IMG_SIZE],
            image_ready: true,

            pattern_data_lb: 0,
            pattern_data_hb: 0,
            attribute_data_lb: 0,
            attribute_data_hb: 0,
        }
    }

    pub fn write(&mut self, addr: u8, data: u8) {
        match addr {
            0 => { // PPUCTRL
                self.ctrl = data; 
                self.t = (self.t & !0x0C00) | (data as u16 & 0x3) << 10;
            }
            1 => { self.mask = data; }
            2 => { self.status = data; }
            3 => { self.oam_addr = data; }
            4 => { self.oam_data = data; }
            5 => {  //PPUSCROLL
                // Writes to scroll changes xscroll and yscroll
                // depending on the order of writes.
                if self.w  {
                    self.yscroll = data;
                    self.t = (self.t & !0x73E0)  |
                        (((data & 0x07) as u16) << 12) | 
                        (((data >> 3) as u16 & 0x1F) << 5);

                } else {
                    self.xscroll = data;
                    self.x = data & 0x07;
                    self.t = (self.t & 0xFFE0) |  ((data >> 3) as u16);
                }
                self.w = !self.w;
            }
            6 => { //PPUADDR
                self.addr = data; 

                if self.w {
                    self.t = (self.t & 0xFF00) | data as u16;
                    self.v = self.t;
                } else {
                    self.t = (self.t & 0x00FF) | (((data & 0x3F) as u16) << 8);
                }

                self.t &= !(1 << 15);
                self.w = !self.w;
            }
            7 => {  //PPUDATA
                // TODO: this behavior only models PPU r/ws when *not* rendering
                // When rendering, the behavior is different, see wiki.
                self.data = data; 
                self.addressor.write(self.v, data);
                self.v = self.v.wrapping_add(if self.vram_increment_bit() { 32 } else { 1 }) & 0x7FFF;
            }
            _ => panic!("Bad PPU address")
        }

        println!("Writing to {} = {}", addr, data);
    }

    pub fn read(&mut self, addr: u8) -> u8 {
        let ret = match addr { //PPUCTRL
            0 => { 
                self.ctrl 
            } 
            1 => { self.mask }
            2 => { // PPUSTATUS
                self.w = false;
                let temp = self.status;
                self.status &= !(0x80); //Unset vblank flag

                temp
            }
            3 => { self.oam_addr }
            4 => { self.oam_data }
            5 => { self.xscroll }
            6 => { self.addr }
            7 => { self.data }
            _ => panic!("Bad PPU address")
        };
        if addr != 2 {
            println!("Reading from {} = {}", addr, ret);
        }
        ret
    }

    pub fn pending_nmi(&self) -> bool { self.pending_nmi }
    pub fn clear_nmi(&mut self) { self.pending_nmi = false; self.nmi_lineout = false; }

    fn inc_hori(&mut self) {
        // X-increment (when next tile is reached)
        if (self.v & 0x001F) == 31  {
            self.v &= !0x001F;
            self.v ^= 0x0400;
        } else {
            self.v += 1;
        }

        self.v &= 0x7FFF;

    }

    fn inc_vert(&mut self) {
        if (self.v & 0x7000) != 0x7000 {
            self.v += 0x1000;
        } else {
            self.v &= !0x7000;
            let mut y = (self.v & 0x03E0) >> 5;
            if y == 29 { 
                y = 0;
                self.v ^= 0x0800;
            } else if y == 31 {
                y = 0;
            } else {
                y += 1;
            }
            self.v = (self.v & !0x03E0) | (y << 5);
        }

        self.v &= 0x7FFF;
    }

    fn load_shifters(&mut self) {
        let tile_address = 0x2000 | (self.v & 0x0FFF);
        let attribute_address = 0x23C0 | (self.v & 0x0C00) 
            | ((self.v >> 4) & 0x38) 
            | ((self.v >> 2) & 0x07);

        let fine_y = (self.v >> 12) & 0x07;

        let pattern_base = self.base_background_pattern_address();
        let tile =  self.addressor.read(tile_address) as u16;

        let mut attribute = self.addressor.read(attribute_address);
        if (self.v >> 5) & 0x02 != 0 { attribute >>= 4; }
        if  self.v       & 0x02 != 0 { attribute >>= 2; }
        let attribute = attribute & 0x03;

        let pattern_low_addr  = pattern_base | (tile << 4) | 0 | fine_y; 
        let pattern_high_addr = pattern_base | (tile << 4) | 8 | fine_y; 

        self.pattern_data_lb = (self.pattern_data_lb & 0xFF00) | ((self.addressor.read(pattern_low_addr) as u16));
        self.pattern_data_hb = (self.pattern_data_hb & 0xFF00) | ((self.addressor.read(pattern_high_addr) as u16));

        let lo = if attribute & 0b01 != 0 { 0xFF } else { 0x00 };
        let hi = if attribute & 0b10 != 0 { 0xFF } else { 0x00 };

        self.attribute_data_lb = (self.attribute_data_lb & 0xFF00) | lo;
        self.attribute_data_hb = (self.attribute_data_hb & 0xFF00) | hi;
    }

    fn update_shifters(&mut self)  {
        self.pattern_data_lb <<= 1;
        self.pattern_data_hb <<= 1;
        self.attribute_data_lb <<= 1;
        self.attribute_data_hb <<= 1;
    }

    fn draw_tile(&mut self, xpos: usize, ypos: usize) {
        let bit_mux = 0x8000u16 >> self.x;
        let p0 = ((self.pattern_data_lb & bit_mux) != 0) as u8;
        let p1 = ((self.pattern_data_hb & bit_mux) != 0) as u8;
        let bg_pixel = (p1 << 1) | p0;
        

        let a0 = ((self.attribute_data_lb & bit_mux) != 0) as u8;
        let a1 = ((self.attribute_data_hb & bit_mux) != 0) as u8;
        let attr = (a1 << 1) | a0;

        let pallette_addr = if bg_pixel == 0 {
            0x3F00
        } else {
            0x3F00 | ((attr as u16) << 2) | (bg_pixel as u16)
        };
        let mut color_index = (self.addressor.read(pallette_addr) & 0x3F) as usize;

        if self.greyscale() {
            color_index = color_index & 0x30;
        }
        let rgb = self.color_data[color_index];
        
        let output_pixel = (ypos as usize)*IMG_WIDTH + (xpos as usize);
        self.image_out[BYTES_PER_PIXEL*output_pixel+0] = rgb[0];
        self.image_out[BYTES_PER_PIXEL*output_pixel+1] = rgb[1];
        self.image_out[BYTES_PER_PIXEL*output_pixel+2] = rgb[2];
    }

    pub fn tick(&mut self) {
        if !self.enable_sprites() && !self.enable_background() {
            // Only render if mask allows it
            if self.scanline == 1 && self.cycle == 1 {
                self.status |= 0x40; //DEBUG: set sprite 0 flag manually
            }

            if self.scanline == 261 && (280..=304).contains(&self.cycle){
                // vert(v) = vert(t);
                self.v = (self.v & !0x7BE0) | (self.t & 0x7BE0);
            }

            if (0..=239).contains(&self.scanline) || self.scanline == 261 {
                if (2..=257).contains(&self.cycle) || (321..=337).contains(&self.cycle) {
                    self.update_shifters();
                }

                if (2..=257).contains(&self.cycle) || (321..=337).contains(&self.cycle) {
                    if (self.cycle - 1) % 8 == 0 { self.load_shifters(); }
                    if (self.cycle - 1) % 8 == 7 { self.inc_hori(); }
                }

                if self.cycle == 256 {
                    self.inc_vert();
                }

                if self.cycle == 257 { 
                    //horiz(v) = horiz(t);
                    self.v = (self.v & !0x041F) | (self.t & 0x041F); 
                }

                if (1..=256).contains(&self.cycle) && self.scanline < 240 {
                    self.draw_tile(self.cycle-1, self.scanline);
                }
            }
        }


        if self.scanline == 241 && self.cycle == 1 {
            // Set vblank flag
            self.status |= 0x80;
            // Must have NMI enabled in PPUCTRL
            if self.vblank_nmi_enable() {
                // Only trigger NMI on rising edge of STATUS bit.
                if !self.nmi_lineout {
                    self.pending_nmi = true;
                }
                self.nmi_lineout = true;
            }
            self.image_ready = true;
        }

        self.cycle += 1;
        if self.cycle > 340 {
            self.cycle = 0;
            self.scanline += 1;
            if self.scanline > 261 {
                self.scanline = 0;
            }
        }
    }

    pub fn get_image_bytes(&self) -> &Vec<u8> { return &self.image_out; }

    // **
    // CTRL Flags
    // **
    fn base_nametable_addr(&self) -> u8 { self.ctrl & 0x03 }
    fn vram_increment_bit(&self) -> bool { (self.ctrl & (1 << 2)) != 0 }
    fn sprite_pattern_table_base(&self) -> u16 { if (self.ctrl & (1 << 3)) != 0 { 0x1000 } else { 0 }}
    fn base_background_pattern_address(&self) -> u16   { if (self.ctrl & (1 << 4)) != 0 { 0x1000 } else { 0 }}
    fn sprite_size(&self) -> (usize, usize)   { if (self.ctrl & (1 << 5)) != 0 { (8, 8) } else { (8, 16) }}
    fn master_slave_select(&self) -> bool   { (self.ctrl & (1 << 6)) != 0 }
    fn vblank_nmi_enable(&self) -> bool   { (self.ctrl & (1 << 7)) != 0 }
    
    // **
    // MASK flags
    // **
    fn greyscale(&self) -> bool              { return (self.mask & 0x1) != 0; }
    fn show_bg_leftmost_screen(&self) -> bool   { return (self.mask & 0x2) != 0; }
    fn show_sprites_leftmost_screen(&self) -> bool  { return (self.mask & 0x4) != 0; }
    fn enable_background(&self) -> bool         { return (self.mask & 0x8) != 0; }
    fn enable_sprites(&self) -> bool         { return (self.mask & 0x10) != 0; }
    fn emphasize_red(&self) -> bool         { return (self.mask & 0x20) != 0; }
    fn emphasize_green(&self) -> bool         { return (self.mask & 0x40) != 0; }
    fn emphasize_blue(&self) -> bool         { return (self.mask & 0x80) != 0; }
}
