
use std::fmt;

#[derive(Copy, Clone)]
pub enum Instruction {
    ERR,
    LDA, STA, LDX, STX, LDY, STY,
    TAX, TXA, TAY, TYA,
    ADC, SBC,
    DEC, DEX, DEY,
    INC, INX, INY,
    AND, ORA, EOR, BIT,
    ASL, LSR, ROL, ROR, 
    CMP, CPX, CPY,
    BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS,
    JMP, JSP, RTS, BRK, RTI,
    PHA, PHP, PLA, PLP, TSX, TXS,
    CLC, CLD, CLI, CLV, 
    SEC, SEI, SED,
    NOP,
}

impl fmt::Display for Instruction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Instruction::ERR => "???",
            Instruction::ADC => "adc",
            Instruction::SBC => "sbc",
            Instruction::AND => "and",
            Instruction::ORA => "ora",
            Instruction::EOR => "eor",
            Instruction::ASL => "asl",
            Instruction::BCC => "bcc",
            Instruction::BCS => "bcs",
            Instruction::BEQ => "beq",
            Instruction::BMI => "bmi",
            Instruction::BNE => "bne",
            Instruction::BPL => "bpl",
            Instruction::BVC => "bvc",
            Instruction::BVS => "bvs",
            Instruction::CLC => "clc",
            Instruction::CLD => "cld",
            Instruction::CLI => "cli",
            Instruction::CLV => "clv",
            Instruction::BIT => "bit",
            Instruction::CMP => "cmp",
            Instruction::CPX => "cpx",
            Instruction::CPY => "cpy",
            Instruction::DEC => "dec",
            Instruction::DEX => "dex",
            Instruction::DEY => "dey",
            Instruction::INC => "inc",
            Instruction::INX => "inx",
            Instruction::INY => "iny",
            Instruction::LSR => "lsr",
            Instruction::NOP => "nop",
            Instruction::ROL => "rol",
            Instruction::ROR => "ror",
            Instruction::SEC => "sec",
            Instruction::SED => "sed",
            Instruction::SEI => "sei",
            Instruction::PHA => "pha",
            Instruction::PHP => "php",
            Instruction::PLA => "pla",
            Instruction::PLP => "plp",
            Instruction::TSX => "tsx",
            Instruction::TXS => "txs",
            Instruction::TAX => "tax",
            Instruction::TXA => "txa",
            Instruction::TAY => "tay",
            Instruction::TYA => "tya",
            Instruction::LDA => "lda",
            Instruction::LDX => "ldx",
            Instruction::LDY => "ldy",
            Instruction::STA => "sta",
            Instruction::STX => "stx",
            Instruction::STY => "sty",
            Instruction::JMP => "jmp",
            Instruction::JSP => "jsp",
            Instruction::RTS => "rts",
            Instruction::BRK => "brk",
            Instruction::RTI => "rti",
        };
        f.write_str(s)
    }
}
